version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Compile
          command: npx tsc
      - run:
          name: Deploy to DigitalOcean
          command: scp -r build brian@bedoherty.com:/home/brian/SlootBot