version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Compile
          command: npx tsc