version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:eb:24:f6:72:3c:c0:d8:92:6f:99:49:e5:5f:19:f6"

      - checkout

      - run:
          name: Add SSH Hosts
          command: ssh-keyscan bedoherty.com >> ~/.ssh/known_hosts

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Compile
          command: npx tsc
      - run:
          name: Deploy to DigitalOcean
          command: scp -r build brian@bedoherty.com:/home/brian/SlootBot